version: "3.3"

services:
  quizz:
    build: .
    image: hack_courses_quizz
    ports:
      - 5000:5000
    volumes:
      - "./db:/app/db"
    hostname: quizz

  cdn:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./cdn:/usr/share/nginx/html
      - ./cdn/nginx_default_conf.conf:/etc/nginx/conf.d/default.conf:ro
